name: Create Release
run-name: New release from tag ${{ github.ref_name }} by @${{ github.actor }}

on:
  push:
    tags:
      - '[0-9]+\.[0-9]+\.[0-9]+'

jobs:
  run_tests_first:
    uses: WritePoetry/reusable-workflows/.github/workflows/php-tests.yml@v1
    with:
      php_versions: "['8.1','8.2','8.3']"
    secrets: inherit

  call_shared_release:
    needs: run_tests_first
    uses: WritePoetry/reusable-workflows/.github/workflows/release.yml@v1
    permissions:
      contents: write
      packages: read
      actions: read
    secrets: inherit